{
    # Line length
    "MD013": false,
    # Headings should be surrounded by blank lines
    "MD022": false,
    # Multiple headings with the same content
    "MD024": false,
    # Lists should be surrounded by blank lines
    "MD032": false
}
